### ISSUE TITLE
Delete of Group Is Not Working with Large Number of Messages

### ISSUE THREAD

**Issue by bbrandt** [Particular/ServicePulse#1886]
#### Description
We had 17M messages in our error queue.  The various dev teams did not like UX of the ServicePulse and ServiceInsight tools so were not using them.  I am making an attempt to cleanup the error queue and start to work with the teams to address some of these issues.

Using delete of old Failed Message groups I was able to delete around 5M old messages.  But now it looks like the delete process is stuck.  This is what I see:
![image](https://github.com/Particular/ServicePulse/assets/602767/b28f6078-d637-4de4-9c1b-f0dfa30861b8)

This is the group that shows as actively deleting:
![image](https://github.com/Particular/ServicePulse/assets/602767/17dd544e-b370-486a-ba38-3b265413f862)

But if I look at the deleted messages for the last day, I see none:
![image](https://github.com/Particular/ServicePulse/assets/602767/bd91e36d-f734-40dc-9014-bd6da6cfca3e)

#### Expected behavior
Delete should be able to delete.

#### Actual behavior
Delete freezes.

#### Versions
ServicePulse v1.31.1

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Click delete on around 50 failed message groups with sizes ranging from 3M to 50K.

### Relevant log output
Logs in the `/custom-checks` are displaying from 2023?  Here is a sample:
```shell
- Index [QueueAddressIndex] error: Index 'QueueAddressIndex' got corrupted because it failed in writing to a disk with the following exception message: There is not enough space on the disk.
. The index priority was set to Error. (Action: Unknown,  Doc: , At: 2/15/2023 9:48:16 PM)
- Index [QueueAddressIndex] error: Failed to flush index 'QueueAddressIndex'. The index priority was set to Error. Exception: System.IO.IOException: Error during flush for QueueAddressIndex ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Lucene.Net.Store.BufferedIndexOutput.Flush()
   at Lucene.Net.Store.ChecksumIndexOutput.PrepareCommit()
   at Lucene.Net.Index.SegmentInfos.Write(Directory directory)
   at Lucene.Net.Index.IndexWriter.StartCommit(Int64 sizeInBytes, IDictionary`2 commitUserData)
   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData)
   at Raven.Database.Indexing.RavenIndexWriter.Commit(Etag lastEtag, Boolean forceCommit, Boolean considerLastCommitedTime)
   at Raven.Database.Indexing.Index.Flush(Etag highestETag, Boolean forceFlush, Boolean considerLastCommitedTime)
   --- End of inner exception stack trace ---
   at Raven.Database.Indexing.Index.Flush(Etag highestETag, Boolean forceFlush, Boolean considerLastCommitedTime)
   at Raven.Database.Indexing.IndexStorage.FlushIndex(Index value, Boolean onlyAddIndexError) (Action: Unknown,  Doc: , At: 2/15/2023 9:48:16 PM)
- Index [Raven/DocumentsByEntityName] error: Index 'Raven/DocumentsByEntityName' got corrupted because it failed in writing to a disk with the following exception message: There is not enough space on the disk.
. The index priority was set to Error. (Action: Unknown,  Doc: , At: 2/15/2023 9:52:37 PM)
- Index [Raven/DocumentsByEntityName] error: Failed to flush index 'Raven/DocumentsByEntityName'. The index priority was set to Error. Exception: System.IO.IOException: Error during flush for Raven/DocumentsByEntityName ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Lucene.Net.Store.BufferedIndexOutput.Flush()
   at Lucene.Net.Store.ChecksumIndexOutput.PrepareCommit()
   at Lucene.Net.Index.SegmentInfos.Write(Directory directory)
   at Lucene.Net.Index.IndexWriter.StartCommit(Int64 sizeInBytes, IDictionary`2 commitUserData)
   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData)
   at Raven.Database.Indexing.RavenIndexWriter.Commit(Etag lastEtag, Boolean forceCommit, Boolean considerLastCommitedTime)
   at Raven.Database.Indexing.Index.Flush(Etag highestETag, Boolean forceFlush, Boolean considerLastCommitedTime)
   --- End of inner exception stack trace ---
   at Raven.Database.Indexing.Index.Flush(Etag highestETag, Boolean forceFlush, Boolean considerLastCommitedTime)
   at Raven.Database.Indexing.IndexStorage.FlushIndex(Index value, Boolean onlyAddIndexError) (Action: Unknown,  Doc: , At: 2/15/2023 9:52:37 PM)

See: https://docs.particular.net/search?q=servicecontrol+troubleshooting
```
Maybe we have a misconfiguration for log folder between SP and SC.

#### Workarounds
Delete the SC DB?

#### Possible solutions
We need to update to latest SC and SP and start with a clean DB.  Has this issue been resolved in the latest version?

**Comment by mikeminutillo** [comment]
@bbrandt could you please [open a support case](https://particular.net/support) and send through the ServiceControl logs files from the time when you attempted the delete operation. While the UX for deleting message groups is part of ServicePulse, it is ServiceControl which performs the delete.

**Comment by mikeminutillo** [comment]
@bbrandt we have not seen a new support case with this information. We just wanted to check whether you had sent it yet.

**Comment by bbrandt** [comment]
Thanks for checking in @mikeminutillo .  I am closing this for now.  We've decided to hold off on experimenting further with ServiceControl until we get it updated to running in k8s with the rest of our services.  We will wipe what we have in the Windows VM and start clean after that.
