### ISSUE TITLE
Javascript error when attempting to retry a message (version 1.3.2)

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServicePulse#202]
ServicePulse version: 1.3.2

When I attempt to retry an error message, I am getting the following Javascript error in the console:

```
TypeError: arguments[i].replace is not a function
    at join (http://localhost:9090/js/services/services.uri.js:11:55)
    at Object.retryFailedMessages (http://localhost:9090/js/services/services.service-control.js:133:27)
    at Scope.$scope.retrySelected (http://localhost:9090/js/failed_messages/failedMessages.controller.js:182:35)
    at fn (eval at <anonymous> (http://localhost:9090/lib/angular/angular.js:13231:15), <anonymous>:4:230)
    at ngEventDirectives.(anonymous function).$rootScope.compile.element.on.callback (http://localhost:9090/lib/angular/angular.js:23371:17)
    at Scope.parent.$get.Scope.$eval (http://localhost:9090/lib/angular/angular.js:15878:28)
    at Scope.parent.$get.Scope.$apply (http://localhost:9090/lib/angular/angular.js:15978:25)
    at HTMLButtonElement.<anonymous> (http://localhost:9090/lib/angular/angular.js:23376:23)
    at HTMLButtonElement.n.event.dispatch (http://localhost:9090/lib/jQuery/jquery.min.js:3:6466)
    at HTMLButtonElement.n.event.add.r.handle (http://localhost:9090/lib/jQuery/jquery.min.js:3:3241) undefined
```

**Comment by petersgiles** [comment]
@Bishbulb can you give me details of your browser and OS etc?

**Comment by petersgiles** [comment]
I've found the issue, just writing some tests around it.
